### ISSUE TITLE
ptdr t ki ?

### ISSUE THREAD

**Issue by SkwalExe** [jcbevc/varzekbot#1]

**Comment by jcbevc** [comment]
ok bite tu veut quoi bite tu veux me prévenir de quoi bite

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
